#!/bin/bash
# Shell script to check TLS version and certificate expiry

echo | openssl s_client -connect $1:443 -servername $1 -tls1 	&> /dev/null &&echo "TLS 1.0: Supported" ||echo "TLS 1.0: NOT Supported" 
echo | openssl s_client -connect $1:443 -servername $1 -tls1_1 	&> /dev/null &&echo "TLS 1.1: Supported" ||echo "TLS 1.0: NOT Supported"
echo | openssl s_client -connect $1:443 -servername $1 -tls1_2 	&> /dev/null &&echo "TLS 1.2: Supported" ||echo "TLS 1.0: NOT Supported"
echo -n "Cert valid: " &echo | openssl s_client -connect $1:443 -servername $1 -tls1_2 	2> /dev/null | openssl x509 -noout -enddate


